# ============================================================
# Mini Banking System - Application Configuration
# ============================================================

# --- Server ---
server.port=8080
server.servlet.context-path=/api

# --- MS SQL Server ---
# Update these values to match your local SQL Server instance
#database connection
spring.datasource.url=jdbc:mysql://localhost:3306/MiniBankingDB
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver



# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.format_sql=true

# --- JWT ---
# Use a strong 256-bit (32 char) secret key in production ? store in environment variable
app.jwt.secret=MiniBankingSystemSecretKey2024XYZ!SecureEnoughForHS256
app.jwt.expiration-ms=86400000

# --- CORS (allow Angular dev server) ---
app.cors.allowed-origins=http://localhost:4200,http://localhost:3000

# --- Logging ---
logging.level.com.bankingsystem=INFO
logging.level.org.springframework.security=WARN